### ISSUE TITLE
Raycaster hitting shapes in opposite direction

### ISSUE THREAD

**Issue by boolean0101** [snowkit/differ#15] opened 2015-05-24 18:09 UTC
I'm using a raycast with infinite turned off, but the raycast is hitting shapes behind me.

For example, I have a square in the middle of the room. If I'm on the right hand side of the square and face left, I hit the outside of the square the the raycast works. If I face right, the raycast now comes in from (what seems like) infinite distance away from the left and hits the square from the left side.

Facing towards the square:
https://dl.dropboxusercontent.com/u/20830426/differ_facingtoward.png
Facing away from the square:
https://dl.dropboxusercontent.com/u/20830426/differ_facingaway.png

It seems like you can replicate this in the github demo by moving the mouse past the raycaster on the left hand side:
https://dl.dropboxusercontent.com/u/20830426/differ_demobug.png

Is this a bug or a settings issue?

**Comment by underscorediscovery** [comment] 2015-05-24 18:22
Can you try pull and see if it still reproduces after the commit below? 

https://github.com/underscorediscovery/differ/commit/fb6932cb3eee411b99b3f3e900abc0786e28c258

**Comment by boolean0101** [comment] 2015-05-24 18:41
wow that was a fast reply - yep that fixed it!

I noticed that when 'infinite' is turned on the same issue occurs, but I'm not sure if that's by design (I thought it would be infinite from the origin point, but perhaps its just an infinitely long line in both directions?).

Cheers.

**Comment by boolean0101** [comment] 2015-05-24 20:16
To get infinite to work I changed line 287 to the following:

if((ray.infinite && min_u >= 0.0 && min_u != Math.POSITIVE_INFINITY) || (min_u <= 1.0 && min_u >= 0.0))

I don't know if this is the best way of doing it but it seems to work. It appears that min_u only gets modified if an intersection is detected. What I did was change line 287 so that it only returns a  collision if infinite is set and if min_u has been updated because of a collision.

I don't know if I'm misunderstanding how infinite works, but it seems to be working for me :)

**Comment by underscorediscovery** [comment] 2016-09-19 02:38
This should all be fixed in 1.3.0, see the https://snowkit.github.io/differ/demo/ under the ray example, as it covers all the use cases intended!

**Closed by underscorediscovery** 2016-09-19 02:38 UTC
